### PR TITLE
[5.4] Switch branch-based dependencies from `main` to `release/5.4`.

### PR DESCRIPTION
**Pull request by abertelrud**
In the `release/5.4` branch, also switch the branch-based dependencies to the `release/5.4` branch.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]

**Comment by abertelrud** [comment]
Thanks @artemcm.  Who else will need to approve it at this point in the 5.4 release schedule?

**Comment by abertelrud** [comment]
@DougGregor Do we need Ben's approval for this?

**Review by DougGregor — APPROVED** [review]
Approved, thank you!

**Comment by DougGregor** [comment]
> @DougGregor Do we need Ben's approval for this?

Nope, please go ahead.

**Comment by abertelrud** [comment]
Great, thanks!

**Pull request merged**
