### PR TITLE
Add support for reading fine-grained source file dependency graphs

### PR DESCRIPTION
**Pull request by owenv**
This just ports over the parts of the source file fine-grained dependency graph the driver cares about. I just called it `SourceFileDependencyGraph` because I assume we don't intend to support the older dependency system. I'm still learning how all this works in the C++ driver, so I'm open to feedback on the API and approach!

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci test

**Comment by owenv** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by davidungar** [comment]
Looks good! Thanks.

**Pull request merged**
