### PR TITLE
Add support for swift caching with path remapping and builtin cache replay

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Retry add swift caching support.

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
Add a workaround for swift package manager if the option to disable implicit concurrency is still required.

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]
Doing a cross-repo test from the `swift` repo can validate the previous failure, I think.

**Comment by artemcm** [comment]
> Doing a cross-repo test from the `swift` repo can validate the previous failure, I think.

And/Or  from the `swiftpm` repo.

**Comment by cachemeifyoucan** [comment]
Cross repo here: https://github.com/apple/swift-package-manager/pull/7125

**Comment by cachemeifyoucan** [comment]
Cross repo testing passing now. Let's try again. Feel free to revert directly if anything else break.

**Pull request merged**
