### PR TITLE
Rework printActions to be more like how the actions are created

### PR DESCRIPTION
**Pull request by cltnschlosser**
Fixes:
Driver/actions.swift
Driver/actions-dsym.swift
Driver/bridging-pch.swift now fails on the output not having -* at the end.

Also fix issue where linker was being passed swiftmoduledoc and swiftsourceinfo files. (As far as I can tell they were ignored)

### CODE REVIEW

**Review by nkcsgexi — APPROVED** [review]
Thank you for fixing this, @cltnschlosser !

**Review by artemcm — APPROVED** [review]
Awesome. Thank you, @cltnschlosser.

**Comment by cltnschlosser** [comment]
@swift-ci please test

**Comment by cltnschlosser** [comment]
> @swift-ci please test

Still not working
Nudge @shahmishal 😀

**Comment by shahmishal** [comment]
> > @swift-ci please test
> 
> 
> 
> Still not working
> 
> Nudge @shahmishal 😀

Let me double check tonight, it should have been working.

**Comment by shahmishal** [comment]
@cltnschlosser Please try again

**Comment by cltnschlosser** [comment]
@swift-ci please test

**Comment by cltnschlosser** [comment]
Thanks @shahmishal !

**Pull request merged**
