### PR TITLE
Use libSwiftScan to query supported compiler flags in-process

### PR DESCRIPTION
**Pull request by artemcm**

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Review by owenv — APPROVED** [review]

**Comment by nkcsgexi** [comment]
Thank you!

**Comment by DougGregor** [comment]
This is causing CI failures, e.g., https://ci.swift.org/job/swift-syntax-PR-macOS/1447/console

**Pull request merged**
