### PR TITLE
[Explicit Module Builds] Rely on the dependency scanner to produce complete compile commands for Swift dependencies

### PR DESCRIPTION
**Pull request by artemcm**
This change removes instances where the driver modified command-line invocations used to build Swift module dependencies, as produced by the dependency scanner. Instead, the scanner will now emit command line argument sets that are sufficient to build all such module dependencies out-of-the-box, including explicit dependency inputs.

The scanner adopts (https://github.com/apple/swift/pull/63460) newly-(re-)added `-swift-module-file` to specify explicit Swift interface dependencies' explicit dependencies. The driver continues using `-explicit-swift-module-map-file` JSON file input to specify all explicit dependencies for the main module's compilation commands (emit-module, compile, etc.), furthermore moving prebuilt Clang dependencies to also appear in this file, thanks to @allevato's change in https://github.com/apple/swift/pull/63178.

### CODE REVIEW

**Comment by artemcm** [comment]
We should wait a fair bit to merge this, at least until https://github.com/apple/swift/pull/63460 makes it to a toolchain snapshot picked up by CI.

**Comment by artemcm** [comment]
https://github.com/apple/swift/pull/63460 has made it to a nightly toolchain. (`swift-DEVELOPMENT-SNAPSHOT-2023-02-09-a `)

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
Not to be merged until https://github.com/apple/swift/pull/63697 lands, otherwise Explicit Modules functionality will be limited.

**Review by nkcsgexi — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci test

**Pull request merged**
