### PR TITLE
Support -file-compilation-dir

### PR DESCRIPTION
**Pull request by pofat**
The origin [PR](https://github.com/apple/swift-driver/pull/968) is merge into main. 
In short, this flag gives us identical debug info paths regardless of what location we compiled the file from.
It's a small but useful feature, and hope it can happen on Swift 5.6.
The PR to merge into Swift 5.6 in Swift is [here](https://github.com/apple/swift/pull/41062)

Resolves [SR-5694](https://bugs.swift.org/browse/SR-5694).

### CODE REVIEW

**Comment by pofat** [comment]
hello @adrian-prantl @artemcm , I hope this can be merged into Swift 5.6 branch. What's the process to request approval? Thank you.

**Review by adrian-prantl — APPROVED** [review]
There's not risk of breaking anything here, since this adds a new option.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by pofat** [comment]
@adrian-prantl tests all passed, would you merge this PR for me?

**Pull request merged**
