### PR TITLE
[Incremental] More efficient sorting

### PR DESCRIPTION
**Pull request by davidungar**
Thanks to @CodaFi for pointing out the opportunity and the fix!

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please test

**Review by CodaFi — APPROVED** [review]
Some nits: Could you drop the extra space between the call and its argument list and clean up the commit message. It doesn't have to be prosaic, but some context would be nice.

**Comment by davidungar** [comment]
> Thanks, @CodaFi , for a speedy approval!

Happy to fix the nits!

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@swift-ci please test macOS platform

**Comment by davidungar** [comment]
rdar://77998890

**Pull request merged**
