### PR TITLE
Remove spaces in source file paths

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Review by cltnschlosser — APPROVED** [review]
Haha, which tool did you try to use that didn't handle spaces correctly?

**Comment by nkcsgexi** [comment]
@cltnschlosser I found it's not handy when navigating to a particular source file in command line.

**Review by davidungar — COMMENTED** [review]
Thank you for catching this! LGTM!

**Pull request merged**
