### PR TITLE
[Dependency Scanning] Pass the bridging header path to scanning action invocations

### PR DESCRIPTION
**Pull request by artemcm**

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
Suspect this may need https://github.com/apple/swift/pull/63831/files to land in the toolchain picked up by CI.

**Comment by artemcm** [comment]
We can also do better here by only specifying bridging header's own dependencies as inputs to the GeneratePCH job. Instead of all of the dependencies of the main module. That way this job will be able to run potentially much sooner than the main compilation. Looking into that as well.

**Review by nkcsgexi — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test Windows platform

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by cachemeifyoucan** [comment]
> We can also do better here by only specifying bridging header's own dependencies as inputs to the GeneratePCH job. Instead of all of the dependencies of the main module. That way this job will be able to run potentially much sooner than the main compilation. Looking into that as well.

That would so super welcomed too. Currently I need to figure out how to pass the PCH from within one `swift-frontend` invocation to clang Importer. If we can move PCH to an individual job that can run much sooner, it can be a cleaner solution for caching

**Pull request merged**
