### PR TITLE
CODE_OF_CONDUCT

### PR DESCRIPTION
**Pull request by gaushikmr**

### CODE REVIEW

**Comment by gaushikmr** [comment]
@owenv Ok I will change it

**Comment by gaushikmr** [comment]
@owenv I have updated it pls check

**Comment by owenv** [comment]
@gaushikmr thanks! It looks like the introduction paragraph may have gotten removed, could you update it to match the one from https://github.com/apple/swift/blob/master/CODE_OF_CONDUCT.md? Once that's done this should be good to go.

**Comment by akyrtzi** [comment]
As @benlangmuir suggested in https://github.com/apple/sourcekit-lsp/pull/302, could we have a link to the swift project document instead of maintaining a separate copy?

**Comment by DougGregor** [comment]
I agree with linking, so we don't have to update everywhere

**Comment by gaushikmr** [comment]
@akyrtzi @DougGregor Ok I will update it

**Comment by shahmishal** [comment]
The Swift project moved the default branch to `main` and deleted `master` branch, so GitHub automatically closed the PR. Please re-create the pull request with `main` branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
