### PR TITLE
Add comment to `getLast` to explain `mutating`

### PR DESCRIPTION
**Pull request by davidungar**

### CODE REVIEW

**Comment by davidungar** [comment]
@swfit-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by davidungar** [comment]
@swift-ci smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by owenv** [comment]
I think "smoke test" doesn't work in this repo, just "test" should work though

@swift-ci please test

**Comment by davidungar** [comment]
@owenv Thanks a lot!

**Pull request merged**
