### PR TITLE
Attempt to unbreak the build by building SwiftDriver module with `-enable-testing` in CMake.

### PR DESCRIPTION
**Pull request by artemcm**
Pass `-enable-testing` to SwiftDriver CMake build to allow the tests to be built on Linux in the presence of `@testable`.
Linux build bots are otherwise failing with:
```
/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-main/swift-driver/Tests/SwiftDriverTests/IncrementalCompilationTests.swift:15:18: error: module 'SwiftDriver' was not compiled for testing
```
Tests relying on `SwiftDriver` were disabled in #364. This PR restores these tests.

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]

**Comment by cltnschlosser** [comment]
Do we build in release configuration? (https://bugs.swift.org/browse/SR-1354)

I ran into this just now too when running the integration tests with spm (This fixed there):
```diff
diff --git a/README.md b/README.md
index b17beb4..442acaf 100644
--- a/README.md
+++ b/README.md
@@ -88,7 +88,7 @@ on the command line:
 ```
 $ SWIFT_DRIVER_ENABLE_INTEGRATION_TESTS=1 \
   SWIFT_DRIVER_LIT_DIR=/path/to/build/Ninja-ReleaseAssert/swift-.../test-... \
-  swift test -c release --parallel
+  swift test -c release -Xswiftc -enable-testing --parallel
 ```
 
 #### Testing against `swift` compiler trunk
```

**Comment by artemcm** [comment]
I think in this case the problem is a little bit different, here the CMake build (not part of the `test` stage, but rather part of the `build` stage in `build-script`), on Linux, is building files that belong to the test targets. And that breaks if the imported module has not been built with `-enable-testing`

**Comment by cltnschlosser** [comment]
Ah, does it need to build the tests?

So with this change we build with testability when doing things like building a toolchain? If yes, do we have a long term plan for getting rid of `@testable`?

**Comment by artemcm** [comment]
Yeah that's a good question, and I definitely don't think this is anything workable long-term. This has been a bit of a perfect storm where our use of `SPI` caused build breaks with newest development compilers, and it was easier to remove that than debug the compiler, to unblock the build. Then we replaced it with `Testable` which had the effect this PR is trying to fix.

Long term, we should absolutely move away from `Testable` and do this properly, probably with library evolution and `spi` combination. This change is a very temporary workaround to get folks' PR tests working.

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
Ah, macOS PR testing seems to have failed with this:
```
/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-main/swift-driver/Tests/SwiftDriverTests/IncrementalCompilationTests.swift:15:18: error: module 'SwiftDriver' was not compiled for testing
21:39:25 @testable import SwiftDriver
21:39:25 ~~~~~~~~~~       ^
21:39:25 error: fatalError
21:39:25 xcrun --sdk macosx --show-sdk-path
```

**Comment by DougGregor** [comment]
Folks, we can't have PR testing broken. I'm going to land https://github.com/apple/swift-driver/pull/364 to disable the code with `@testable import` in it and we can sort this out on Monday.

**Comment by DougGregor** [comment]
Make sure to revert https://github.com/apple/swift-driver/pull/364 before tackling this.

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
