### PR TITLE
[5.7] Explicitly copy defsIDependUpon into an appropriately sized array when initializing SourceFileDependencyGraph.Node

### PR DESCRIPTION
**Pull request by owenv**
5.7 cherry pick of https://github.com/apple/swift-driver/pull/1119

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci please test

**Comment by owenv** [comment]
This is now updated with the additional type annotation needed to compile in regular swift CI

**Comment by owenv** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]

**Pull request merged**
