### PR TITLE
[Incremental] Add sdk arguments to incremental tests

### PR DESCRIPTION
**Pull request by davidungar**
The latest Swift makes tests fail because it cannot load libraries. Point the frontend to the sdk for the incremental tests. Add an affordance to do so. More tests will probably need to use this affordance in the future.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please test

**Review by CodaFi — APPROVED** [review]

**Comment by CodaFi** [comment]
(Barring the Linux failure, which just needs an extra check for `xcrun`'s existence)

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
> (Barring the Linux failure, which just needs an extra check for `xcrun`'s existence)

Thanks!

**Comment by davidungar** [comment]
@swift-ci please test

**Pull request merged**
