### PR TITLE
Always apply working-directory in the swift-driver

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Consistently apply working-directory even if the option is not explicitly passed. This ensures the created swift-frontend invocations can be executed anywhere without worrying about what the current directory is.

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test windows platform

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test windows platform

**Comment by cachemeifyoucan** [comment]
@swift-ci please test windows platform

**Comment by cachemeifyoucan** [comment]
@swift-ci please test windows platform

**Review by artemcm — APPROVED** [review]
I think this is reasonable.

**Pull request merged**
