### PR TITLE
Always run tests in parallel

### PR DESCRIPTION
**Pull request by keith**
This came from the python2 -> python3 conversion and https://github.com/apple/swift-driver/pull/1087

### CODE REVIEW

**Comment by keith** [comment]
Using https://github.com/apple/swift/pull/58535 to test, not sure if this would catch it. @DougGregor it looks like this was from your initial commit, any recollection on how it repro'd?

**Comment by keith** [comment]
@swift-ci please test

**Comment by keith** [comment]
Integration did pass on this @artemcm

**Comment by artemcm** [comment]
> Integration did pass on this @artemcm

:shipit:

**Review by artemcm — APPROVED** [review]

**Pull request merged**
