### PR TITLE
SwiftOptions: regenerate the swift options

### PR DESCRIPTION
**Pull request by compnerd**
Regenerate the swift options from the C++ driver to pick up changes for the new Windows options that are being introduced to control the SDK and Visual C++ tools that we use.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]
Worth adding logic that only adds these flags to frontend invocations when they support the new flags? 
e.g. https://github.com/apple/swift-driver/pull/1302/files

**Comment by compnerd** [comment]
I like that idea!  I can do that as part of the change that forwards the argument.

**Comment by zoecarver** [comment]
Thanks Artem, I guess that's why #1306 is also failing. I will fix that test in that PR but will likely cause merge conflicts over here :/ Sorry, Saleem.

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Pull request merged**
