### PR TITLE
Fix compile when using Xcode 12.4

### PR DESCRIPTION
**Pull request by cltnschlosser**
It's the latest approved version of Xcode in apple/swift, so makes sense that swift-driver should build when using it.

### CODE REVIEW

**Review by CodaFi — APPROVED** [review]
Give this a quick rebase and we'll get it merged.

**Comment by cltnschlosser** [comment]
Rebased. Reverted my changes to one of the files and went with the approach on main branch.

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
