### PR TITLE
[Build Script Helper] On macOS make install action use CMake and install libSwiftDriver

### PR DESCRIPTION
**Pull request by artemcm**
Previously only the x86 `swift-driver` and `swift-help` executables were copied over to the specified toolchain's `bin` directory.
With this change, `libSwiftDriver` shared library is also packaged and installed into the toolchain, as well as `libSwiftOptions`.
To do so, we build the driver and all of its dependencies using CMake for `arm64` and `x86_64` and create universal binaries, as documented [here](https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary).

Because the driver's dependencies need to come along for the ride, the installed artifacts are as follows, within the specified toolchain:
#### Executables:
```
bin/swift-driver
bin/swift-help
```
#### Binary Modules and Shared Libraries 
```
lib/swift/macosx/libTSCBasic.dylib
lib/swift/macosx/libTSCLibc.dylib
lib/swift/macosx/libTSCUtility.dylib
lib/swift/macosx/libSwiftDriver.dylib
lib/swift/macosx/libSwiftOptions.dylib

lib/swift/macosx/TSCBasic.swiftmodule
lib/swift/macosx/TSCLibc.swiftmodule
lib/swift/macosx/TSCUtility.swiftmodule
lib/swift/macosx/SwiftDriver.swiftmodule
lib/swift/macosx/SwiftOptions.swiftmodule
```
#### C Module .modulemap and header files
```
include/swift/TSCclibc/*
```
#### Misc
- The `Yams` dependency is `implementationOnly` and is built as a static-library.
- `ArgumentParser.swiftmodule` and `libArgumentParser.dylib` must also be installed into the toolchain, but the code currently omits them, to avoid adding them to the toolchain until they are actually needed. 

Resolves rdar://69708243

### CODE REVIEW

**Comment by artemcm** [comment]
Two blockers for this, currently:
- Building `swift-driver` with library-evolution enabled fails because the compiler prints unqualified types for type extensions to the interface file and we are extending `TSCBasic.Process`, which is ambiguous with `Foundation.Process`. Brent has a fix PR to make the compiler print qualified extension type names here: https://github.com/apple/swift/pull/32780, but just throwing this fix in I am seeing other failures. More investigation needed. 
- Without library-evolution, the installation works for me locally, but does not work in Swift CI (e.g. here: https://github.com/apple/swift/pull/33918) because when building `LLBuild`, my local build figures out to use Xcode SDK's version of libSQLite, whereas in CI, the build uses the one in `/usr/local/lib/`, which only has an x86_64 slice so the arm64 build fails.

**Comment by nkcsgexi** [comment]
@artemcm Just discussed @DougGregor about this, we could first disable `-enable-library-evolution` for now and use the binary module format for submission. The build system can link against libSwiftDriver in the default toolchain so we could start experimenting with the explicit module feature. Multiplexing libSwiftDriver can be a concern we tackle some point later.

**Comment by artemcm** [comment]
@shahmishal , For the second point in the above point,  

> @artemcm Just discussed @DougGregor about this, we could first disable `-enable-library-evolution` for now and use the binary module format for submission. The build system can link against libSwiftDriver in the default toolchain so we could start experimenting with the explicit module feature. Multiplexing libSwiftDriver can be a concern we tackle some point later.

Sounds good! I'll push through with resolving the remaining issues without using `-enable-library-evolution`.

**Comment by nkcsgexi** [comment]
> > @artemcm Just discussed @DougGregor about this, we could first disable `-enable-library-evolution` for now and use the binary module format for submission. The build system can link against libSwiftDriver in the default toolchain so we could start experimenting with the explicit module feature. Multiplexing libSwiftDriver can be a concern we tackle some point later.
> 
> Sounds good! I'll push through with resolving the remaining issues without using `-enable-library-evolution`.

Thank you!

**Comment by artemcm** [comment]
This is currently functional (I can build a simple swift program that imports and uses `SwiftDriver` by pointing library and include paths to the built toolchain). 
In our chat, @nkcsgexi brought up a good point that we should probably be able to refactor `SwiftDriver` into a client library for build systems that does not itself depend on `llbuild`. We can do this refactoring as either a follow-up or a pre-requisite to this change.

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
Note: This must be merged in tandem with: https://github.com/apple/swift/pull/33918

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
This all looks reasonable to me.  Thank you!

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
