### PR TITLE
Replace 'ParsableMessage' factory methods with an initializer.

### PR DESCRIPTION
**Pull request by rxwei**
This PR uses an initializer `init(name:kind:)` to unify multiple factory methods.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
What if we changed each of these methods to drop the redundant type name, move the `message:` parameter first, then drop the redundant label there too?

```
ParsableMessage.signalled(signalledMessage, named: job.name.rawValue)
```

**Comment by rxwei** [comment]
I like that idea.  But after giving some more thoughts to this, I think it might be better to drop these static methods and just use initializers instead, since it isn't more complicated:
```swift
ParsableMessage(name: job.kind.rawValue, kind: .signalled(message))
```

What do you think?

**Comment by harlanhaskins** [comment]
That sounds great to me.

**Comment by rxwei** [comment]
Done.

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@swift-ci please test

**Pull request merged**
