### PR TITLE
Turn on emit-module-separately for whole-module builds by default

### PR DESCRIPTION
**Pull request by xymus**
Scheduling a separate emit-module job for whole-module builds, combined with the integrated driver in the build system, will allow to parallelize what used to be essentially sequential builds. This mode unblocks building dependents early by duplicating some work in two processes, it requires more cpu work for a faster wall clock build time. Another advantage of this mode is the resulting swiftmodule is lighter from a classic whole-module build.

rdar://85976762

### CODE REVIEW

**Comment by xymus** [comment]
I put this up as is to run tests. I expect this to break a lot of tests, here and in the driver.

@swift-ci Please test

**Comment by xymus** [comment]
@swift-ci Please test

**Comment by xymus** [comment]
@swift-ci Please test

**Comment by xymus** [comment]
More tests are failing this time, it's a good sign. The first version scheduled the separate emit-module job only when the `-emit-module` flag was passed explicitly, not for other module-wide outputs.

**Comment by xymus** [comment]
@swift-ci Please test

**Comment by xymus** [comment]
@swift-ci Please test

**Comment by xymus** [comment]
The tests look good here and on the compiler side. I think this is ready for review!

**Review by nkcsgexi — APPROVED** [review]

**Comment by artemcm** [comment]
:ship:

**Pull request merged**
