### PR TITLE
Replace remaining uses of `<<<` operator with `.send`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
After merging https://github.com/apple/swift-driver/pull/1444 there are still a few uses of `<<<` left, which should be cleaned up. This fixes remaining deprecation warnings caused by the use of `<<<`.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test macos

**Comment by MaxDesiatov** [comment]
@swift-ci test macos

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test linux

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Review by artemcm — APPROVED** [review]
Thanks, @MaxDesiatov

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
