### PR TITLE
[Explicit Module Builds] Add end-to-end explicit module build compile test

### PR DESCRIPTION
**Pull request by artemcm**
The test invokes the driver using `-experimental-explicit-module-build` and ensures an executable is produced without errors. 

The test runs for a long time because it must compile the `Swift` module, currently just testing how much overhead it will be with CI's toolchain.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
The linux failure is due to the fact that the dependency scanning action is invoked with `-disable-objc-interop`, which causes the scanner to omit emitting a `SwiftShims` dependency for the `Swift` module.

**Comment by DougGregor** [comment]
> The linux failure is due to the fact that the dependency scanning action is invoked with `-disable-objc-interop`, which causes the scanner to omit emitting a `SwiftShims` dependency for the `Swift` module.

Can you conditionality the test?

**Comment by artemcm** [comment]
> > The linux failure is due to the fact that the dependency scanning action is invoked with `-disable-objc-interop`, which causes the scanner to omit emitting a `SwiftShims` dependency for the `Swift` module.
> 
> Can you conditionalize the test?

Do you mean make it run on macOS only?

**Comment by DougGregor** [comment]
> Do you mean make it run on macOS only?

No, I mean either don't check for SwiftShims, or only check for SwiftShims on Darwin

**Comment by artemcm** [comment]
I don't think I can change this at the test-level. The test compiles the `Swift` module, which will look for a `SwiftShims` module but will not find it (and error out) because 1. Implicit lookup is disabled, 2. `SwiftShims` is not provided explicitly because the scanner omitted it due to `disable_objc_interop` on Linux.

**Comment by artemcm** [comment]
@DougGregor there's not a good way to get the dependency scanner working on Linux until Clang starts providing a by-name module lookup API. While that's being built, should we check this in for macOS only for now?

**Comment by DougGregor** [comment]
I'm fine with checking only for macOS now while we await a Clang API to do by-name module lookup. That `.m` file with an `@import` is a really gross hack.

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
