### PR TITLE
Make swift driver friendlier to relative paths

### PR DESCRIPTION
**Pull request by zienag**
Add handling for relative paths in output file map path,
resonse file paths, recorded input modification dates.

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci test

**Comment by owenv** [comment]
@zienag sorry for taking so long to come back to this. It looks one of the response file tests is failing on CI

**Comment by zienag** [comment]
> @zienag sorry for taking so long to come back to this. It looks one of the response file tests is failing on CI

Hmm, that is unfortunately non trivial bug: given arguments 
```
swiftc -Xlinker @SOMETHING
```
`expandResponseFiles` would think that `@SOMETHING` is response file passed to driver. Before my changes it tried to make absolute path from `SOMETHING`, failed and skipped that argument. Now it makes relative path from `SOMETHING` and tries to read its content. This behaviour is totally wrong, and likely deserves separate pr.

Do you know any code/place that works with `-Xblabla arg` arguments to ignore or filter them out in `expandResponseFiles`?

**Comment by zienag** [comment]
Meanwhile, I'll remove changes associated with response file from this pr, as extensions I've added are needed by other prs

**Comment by owenv** [comment]
@zienag unfortunately I don't have a good idea about how to handle -X... arguments with response files. This might cause problems when we eventually migrate to swift-argument-parser too. In the meantime, the rest of this change will still be really helpful though!

**Comment by owenv** [comment]
@swift-ci test

**Comment by owenv** [comment]
@swift-ci test

**Comment by owenv** [comment]
Looks like the checks are all passing now. Thanks @zienag !

**Pull request merged**
