### PR TITLE
test SymbolGraph/EmitWhileBuilding when a lit dir is available

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
As part of rdar://76815547, i want to make sure the symbol-graph's integration into the frontend is properly flexed with both the old driver and the new driver.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by artemcm** [comment]
@QuietMisdreavus , could you please run a cross-repository test as described in:
https://github.com/apple/swift-driver#testing-against-swift-compiler-trunk

Just to make sure that merging this won't block the compiler's CI.

**Comment by QuietMisdreavus** [comment]
@artemcm I did that as part of https://github.com/apple/swift/pull/37017 - should i run another one with the current state of swift/main?

**Comment by QuietMisdreavus** [comment]
A test has been performed with the current status of swift/main: https://github.com/apple/swift/pull/37132

**Review by artemcm — APPROVED** [review]

**Pull request merged**
