### PR TITLE
Add support for emitting Source Info Files

### PR DESCRIPTION
**Pull request by artemcm**

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
What's a Source Info file?

**Comment by nkcsgexi** [comment]
> What's a Source Info file?

It's serialized source locations for decls in a .swiftmodule file. We use it to emit diagnostics across module boundaries in a local development environment. Not sure it's very relevant for .swiftmodule generated from .swiftinterface though.

**Comment by DougGregor** [comment]
> It's serialized source locations for decls in a .swiftmodule file. We use it to emit diagnostics across module boundaries in a local development environment. Not sure it's very relevant for .swiftmodule generated from .swiftinterface though.

Oh, thank you! I thought it was something new I didn't know about ;)

**Comment by cltnschlosser** [comment]
Does this fix some lit test? Can we add a test here.

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
