### PR TITLE
Add additional valid args to sanitize-coverage flag

### PR DESCRIPTION
**Pull request by thetruestblue**
Adds valid arguments to -sanitize-coverage: `pc-table` and `inline-8bit-counter`. 

As is, you cannot set all default fuzzer options directly using -sanitize-coverage. Because of this you can use default fuzzer sanitize-coverage args, or a limited number coverage options. 

This PR adds options to allow `pc-table` and `inline-8bit-counter` as valid args. These are default fuzzer options -- and will allow customizing sanitizer-coverage in variations of fuzzer defaults. (i.e. w/o `pc-table` enabled).

In upstream clang the option -fno-sanitize-coverage exists to disable various coverage options. Swift currently does not have a convention of using excluding args for sanitizer flags. This aims to limit the need for a new flag by inclusively setting desired coverage up to current fuzzer defaults.

corresponding change in swift: https://github.com/apple/swift/pull/73587

rdar://127950283

### CODE REVIEW

**Comment by thetruestblue** [comment]
@swift-ci test

**Review by owenv — APPROVED** [review]

**Comment by thetruestblue** [comment]
@swift-ci test

**Comment by thetruestblue** [comment]
@swift-ci please test Windows

**Comment by thetruestblue** [comment]
@swift-ci please test Windows

**Comment by thetruestblue** [comment]
@swift-ci test

**Comment by thetruestblue** [comment]
@swift-ci please test Windows

**Review by usama54321 — APPROVED** [review]

**Pull request merged**
