### PR TITLE
Remove extra options and regenerate from Swift's Options.td

### PR DESCRIPTION
**Pull request by bnbarham**
Remove `ExtraOptions.swift` to avoid new options being added there and
not in the old driver, at least until all clients are moved off the old
driver completely.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
I've moved all the options into Options.td in https://github.com/apple/swift/pull/60813. This is the result of re-running `makeOptions` + removing `ExtraOptions`.

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
I'm not sure if this is worth it or not without enforcing options not being added to `Options.swift` either (eg. `-nostartfiles`)... But since we discussed it I've put it up anyway.

**Review by artemcm — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
Looks like this broke the CMake build, fixing in https://github.com/apple/swift-driver/pull/1166

**Pull request merged**
