### PR TITLE
Pass down the `-Rmodule-loading` flag to the frontend

### PR DESCRIPTION
**Pull request by xymus**

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please test

**Comment by xymus** [comment]
@swift-ci Please test

**Review by artemcm — APPROVED** [review]

**Comment by xymus** [comment]
```
mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "dispatch_overcommit.exe". Access is denied.
```

@swift-ci Please test Windows

**Comment by artemcm** [comment]
CI is _stressed_ today.

**Pull request merged**
