### PR TITLE
Bumped minimum platform version to 10.13 

### PR DESCRIPTION
**Pull request by sstadelman**
Required for PR [Support for Netrc for Downloader](https://github.com/apple/swift-tools-support-core/pull/88)  & [SPM mirror](https://github.com/apple/swift-package-manager/pull/2833).
Discussed: [SPM support basic auth for non-git binary dependency hosts](https://forums.swift.org/t/spm-support-basic-auth-for-non-git-binary-dependency-hosts/37878/10?u=sstadelman).

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by sstadelman** [comment]
@artemcm is there another process for merging this once approved/checked?

**Comment by artemcm** [comment]
@sstadelman, There is no further process.
But, I think the intent was to have this merged in tandem with the corresponding SwiftPM change (https://github.com/apple/swift-tools-support-core/pull/88), right?  
With only this merged, and the SwiftPM piece not yet merged, SwiftPM trunk cannot be built against swift-driver trunk because:
```
error: the library 'Build' requires macos 10.10, but depends on the product 'SwiftDriver' which requires macos 10.13; consider changing the library 'Build' to require macos 10.13 or later, or the product 'SwiftDriver' to require macos 10.10 or earlier.
```

**Comment by sstadelman** [comment]
@artemcm looks like it was already merged, but yes, this will have a chain effect.  SPM can bump its platform minimum version, independent of the PR#88.  If there's a hold on PR#88 that will be necessary.

**Comment by sstadelman** [comment]
no longer required for netrc support.

**Pull request merged**
