### PR TITLE
Enable cmake install target on all platforms

### PR DESCRIPTION
**Pull request by gmittert**
Summary: The CMake files look like they are copied over from the SwiftPM
CMake which does some custom installation when it bootstraps itself on
non Windows platforms. Swift-driver doesn't do this, so there's no need
to hide the install target on non Windows platforms.

### CODE REVIEW

**Comment by gmittert** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
Glad we didn't need the hack, thanks!

**Comment by gmittert** [comment]
@DougGregor can you merge this for me please? I don't have write access to swift-driver.

**Comment by DougGregor** [comment]
> @DougGregor can you merge this for me please? I don't have write access to swift-driver.

Done!

**Pull request merged**
