### PR TITLE
Fix up self-discovery of Swift Driver and tools

### PR DESCRIPTION
**Pull request by stevapple**
The `arguments` is modified by `Driver.invocationRunMode`, so the first element is no longer the driver itself.

I’m surprised that no one has discovered this so far👀

### CODE REVIEW

**Comment by stevapple** [comment]
Question: Why were we replacing the arguments here?

The subsequence is that after replacing `/path/to/swift build` with `swift-build`, SwiftPM cannot know its real path, causing tools to be not found.

**Comment by stevapple** [comment]
cc @artemcm

**Comment by stevapple** [comment]
Ping

**Comment by artemcm** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]
This looks correct to me, thank you.

**Comment by stevapple** [comment]
Anyone to merge now?

**Comment by stevapple** [comment]
Ping again for anyone with access to merge:)

**Comment by stevapple** [comment]
@artemcm It seems ready for merge now?

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
```
C:\Users\swift-ci\jenkins\workspace\swift-driver-PR-windows\swift\include\swift/Demangling/Errors.h(23): fatal error C1083: Cannot open include file: 'swift/shims/Visibility.h': No such file or directory
```
@compnerd does this look familiar?

**Comment by compnerd** [comment]
Yes that seems familiar.  https://github.com/apple/llvm-project/pull/5321 should have addressed that.  https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/ is also green currently.

**Comment by artemcm** [comment]
A subsequent build passed. 👍🏼

**Pull request merged**
