### PR TITLE
[Incremental] Redoing do incremental builds

### PR DESCRIPTION
**Pull request by davidungar**
Redoing https://github.com/apple/swift-driver/pull/329 with a Linux-proof test

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please test linux

**Comment by davidungar** [comment]
@swift-ci please test macos platform

**Review by artemcm — APPROVED** [review]
Great! 👍

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
> Great! 👍

Thanks!

**Pull request merged**
