### PR TITLE
test: skip testAPIComparisonEndToEnd() while investigating

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://82302797

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
Ah, this `XCTSkip` is on the wrong test. It needs to be on `testABIComparisonEndToEnd`, not `testAPIComparisonEndToEnd`.

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
I guess it needs to be on both, sorry. :(

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@artemcm no worries at all. Thanks for pinging!

**Pull request merged**
