### PR TITLE
Revert "Refactor job response file handling to (hopefully) prevent regressions."

### PR DESCRIPTION
**Pull request by nkcsgexi**
Reverts apple/swift-driver#1036

cc: @allevato @artemcm 

Sorry that I have to revert this PR. This PR seems to have caused conflicts with our internal repo. We'll investigate how to resolve them and merge this again.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Review by artemcm — CHANGES_REQUESTED** [review]
I don't think this will be necessary, please stand by.

**Comment by nkcsgexi** [comment]
Thanks for fixing this @artemcm !

**Comment by allevato** [comment]
Thanks for finding a fix without needing to revert it!

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
(Sorry, trying to test out a theory)

**Comment by DougGregor** [comment]
Re-closing, sorry for the noise

**Pull request closed without merging**
