### PR TITLE
Pass -warn-on-potentially-unavailable-enum-case frontend flag when building a module

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes rdar://problem/78306593.

### CODE REVIEW

**Comment by slavapestov** [comment]
https://github.com/apple/swift/pull/37843
@swift-ci Please test

**Review by davidungar — APPROVED** [review]
Looks OK to me!

**Review by nkcsgexi — CHANGES_REQUESTED** [review]
Could you check `isFrontendArgSupported` before inserting this flag? swift-driver may work with an earlier version of the compiler.

**Review by DougGregor — APPROVED** [review]

**Comment by slavapestov** [comment]
@nkcsgexi Done!

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by nkcsgexi — APPROVED** [review]
Thanks!

**Pull request merged**
