### PR TITLE
Add REPL support

### PR DESCRIPTION
**Pull request by owenv**
The second commit also adds some special handling for single job build plans when in REPL or immediate mode.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by owenv** [comment]
No problem, I wasn’t thinking when I submitted all of these right before the holidays :) Thanks for taking a look!

**Comment by DougGregor** [comment]
No worries! Holidays are interesting for open source, when paid contributors go on break and volunteer contributors have more free time. Thanks again! Feel free to tag me if you need more review

**Comment by sjavora** [comment]
Hey, @owenv - does this mean `REPL Mode` should be checked off in [the README](https://github.com/apple/swift-driver#development-plan)?

**Comment by owenv** [comment]
@sjavora yeah, thanks for the reminder. I think https://github.com/apple/swift-driver/pull/61 brings the todo list more or less up-to-date

**Pull request merged**
