### PR TITLE
[6.0] Change dependency on swift-tools-support-core to release/6.0

### PR DESCRIPTION
**Pull request by ahoppen**

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by MaxDesiatov — COMMENTED** [review]
Shouldn't this PR have `release/6.0` as the base branch instead of `main`?

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
