### PR TITLE
[Gardening] Delete deprecated API for tracking external target information.

### PR DESCRIPTION
**Pull request by artemcm**
This was in-place as a temporary shim while SwiftPM adapted the `InterModuleDependencyOracle` API and a lighter-weight `ExternalTargetModulePathMap`.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
Cross-repo tests from the Swift and SwiftPM repositories are all green.

**Review by nkcsgexi — APPROVED** [review]
Removing code is always exciting, Thank you!

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
