### PR TITLE
[Incremental] Try a cache for external dependency mod times

### PR DESCRIPTION
**Pull request by davidungar**
Playing a hunch to fix a performance issue. 

rdar://75351845

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
Do we know if this is the root cause?

**Comment by davidungar** [comment]
> Do we know if this is the root cause?

It's suspicious, given the trace in the radar, but I'm waiting to hear from the person reporting the problem to see if it fixes it. I didn't see enough info the radar to reproduce the issue myself.

**Comment by davidungar** [comment]
> Do we know if this is the root cause?

Fixed the issue, 40 secs -> 2 secs.

**Review by CodaFi — APPROVED** [review]
Approved. Please add a regression test that uses a mock file system instance to make sure we don’t see this again.

**Pull request merged**
