### PR TITLE
Revert "File list support"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift-driver#144

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @DougGregor @cltnschlosser

**Review by owenv — APPROVED** [review]

**Comment by cltnschlosser** [comment]
@owenv Just opened this as a fix as well: https://github.com/apple/swift-package-manager/pull/2924 @compnerd

**Comment by compnerd** [comment]
Great, let's fix forward then

**Pull request closed without merging**
