### PR TITLE
Incremental: ensure we add post-compile jobs if no new compile jobs are found

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://74447605

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]
LGTM, @davidungar what do you think?

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Review by davidungar — COMMENTED** [review]
Thank you for looking at this issue 

I suspect that, with this fix, the post-compile jobs would get to run before the compile-pch job finished.

I'm starting to wonder if a better fix is to remove the early return from `addRuleBeyondMandatoryCompiles` and instead to put an early return in `collectJobsDiscoveredToBeNeededAfterFinishing` , returning empty if a non-compile job?

**Comment by davidungar** [comment]
Hate to say it, but I'm now waffling.
Here's what I'm thinking... in a non-incremental build, maybe there would be nothing to sequence the jobs other than llbuild input-output matching. (Is that right?) So, could all the pre-compile jobs just get run in parallel with the post-compile jobs modulo inputs and outputs? If so, your fix is better: unfinishedJobs -> unfinishedCompileJobs.

**Comment by nkcsgexi** [comment]
Ok, let's merge this for now. @davidungar any advice for adding test for this change?

**Review by davidungar — APPROVED** [review]

**Comment by davidungar** [comment]
> Ok, let's merge this for now. @davidungar any advice for adding test for this change?

Good question, @nkcsgexi . I guess we need a test that creates a precompiled header. I would look at `testIncremental` to see what that does. Much of that machinery should be reusable.

**Comment by davidungar** [comment]
One last thought: with this change are we guaranteed that the whole driver process won't terminate before the pch job?

**Comment by artemcm** [comment]
> One last thought: with this change are we guaranteed that the whole driver process won't terminate before the pch job?

I think this job is always going to be a part of the initial set of jobs we submit to llbuild, (not one discovered when other jobs finish), so the `ExecuteAllJobsRule` should ensure it actually gets run before we return from `MultiJobExecutor::execute`.

**Comment by davidungar** [comment]
> > One last thought: with this change are we guaranteed that the whole driver process won't terminate before the pch job?
> 
> I think this job is always going to be a part of the initial set of jobs we submit to llbuild, (not one discovered when other jobs finish), so the `ExecuteAllJobsRule` should ensure it actually gets run before we return from `MultiJobExecutor::execute`.

Thanks! Sounds good to me.

**Pull request merged**
