### PR TITLE
update argument parser to 1.2.x

### PR DESCRIPTION
**Pull request by tomerd**

### CODE REVIEW

**Review by compnerd — COMMENTED** [review]
Please update the other users of s-a-p as well and swift-installer-scripts.  Windows uses a dynamically linked copy of s-a-p that is shared across the driver, SPM, and LSP.

**Comment by tomerd** [comment]
https://github.com/apple/swift/pull/63521
https://github.com/apple/swift-package-manager/pull/6131
https://github.com/apple/sourcekit-lsp/pull/708

@swift-ci test

**Comment by artemcm** [comment]
@tomerd there is no cross-repo testing from here, unfortunately.
You'll need to run it from the main Swift repo and include all of the above plus this PR.

**Comment by allevato** [comment]
@compnerd Does swift-format also need to be updated here?

**Comment by tomerd** [comment]
@artemcm https://github.com/apple/swift/pull/63521

**Comment by compnerd** [comment]
@allevato yes 🙈

**Comment by tomerd** [comment]
https://github.com/apple/swift/pull/63521
https://github.com/apple/swift-package-manager/pull/6131
https://github.com/apple/sourcekit-lsp/pull/708

@swift-ci test

**Pull request merged**
