### PR TITLE
Remove remaining appearences of deprecated 'AbsolutePath' initializer in tests

### PR DESCRIPTION
**Pull request by artemcm**

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Review by nkcsgexi — APPROVED** [review]

**Comment by compnerd** [comment]
We should run this on Windows before submitting.  Unfortunately, the CI is build-only for Windows :-(

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
