### PR TITLE
Only emit ABI descriptors on Darwin platforms

### PR DESCRIPTION
**Pull request by artemcm**
Where Library Evolution is enabled

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]
Thank you!

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
