### PR TITLE
[Incremental Imports] Explain more about invalidation from externals.

### PR DESCRIPTION
**Pull request by davidungar**
`-driver-show-incremental` doesn't show enough information when an external dependency causes recompilation. Fix that.

### CODE REVIEW

**Comment by davidungar** [comment]
I'll be adding a test.

**Review by artemcm — APPROVED** [review]
LGTM!

**Comment by davidungar** [comment]
Since this functionality is only for diagnosing issues, and the test will be a non-trivial addition, will land this now and will write the test in a subsequent PR.

**Comment by davidungar** [comment]
rdar://77662683

**Pull request merged**
