### PR TITLE
[5.10] Remove special handling of the -experimental-lazy-typecheck flag

### PR DESCRIPTION
**Pull request by tshortli**
Cherry pick of https://github.com/apple/swift-driver/pull/1468.

For now, the flag will simply be a frontend flag and the build system will pass it directly using `-Xfrontend` when appropriate.

Resolves rdar://117168788

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test Windows

**Comment by tshortli** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]

**Comment by tshortli** [comment]
@swift-ci please test Windows

**Pull request merged**
