### PR TITLE
Remove legacy libSyntax related options

### PR DESCRIPTION
**Pull request by rintaro**
`-emit-syntax` and `-verify-syntax-tree` are not supported anymore.
See: https://github.com/apple/swift/pull/62132

### CODE REVIEW

**Review by nkcsgexi — APPROVED** [review]
Thank you!

**Comment by artemcm** [comment]
@rintaro, was the `Options` file updated according to the process described here:
https://github.com/apple/swift-driver#rebuilding-optionsswift
?

**Comment by rintaro** [comment]
@artemcm Ah, thanks for pointing out the right procedure. I didn't know it. I just searched the code and removed the options I removed in swift repo. Will try it

**Comment by rintaro** [comment]
@artemcm @nkcsgexi `makeOptions` added bunch of options (and removed one option). Are we OK to just adding them?

**Comment by artemcm** [comment]
@swift-ci test

**Review by artemcm — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by artemcm** [comment]
@swift-ci test Windows platform

**Pull request merged**
