### PR TITLE
Use library search group when linking statically

### PR DESCRIPTION
**Pull request by drexin**
Port of this PR: https://github.com/apple/swift/pull/36356

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test macos

**Comment by owenv** [comment]
Should we pull object file and bitcode inputs out of the linker group on the command line? I think this is only necessary for certain autolink inputs, and the performance impact might be significant.

**Review by artemcm — APPROVED** [review]
Could you please add a change to `testLinking` analogous to the one made to `linker-args-order-linux.swift` to make sure the command line looks right when statically linking?

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@artemcm done

**Comment by drexin** [comment]
@swift-ci test

**Pull request merged**
