### PR TITLE
Revert "Revert "Make the DWARF version configurable.""

### PR DESCRIPTION
**Pull request by adrian-prantl**
Reverts apple/swift-driver#1473

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
Reapplied without modification. The culprit was https://github.com/apple/llvm-project/pull/7694

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
macOS bot is still running into the llbuild issue...

**Review by DougGregor — APPROVED** [review]

**Comment by meg-gupta** [comment]
@swift-ci clean test macOS Platform

**Pull request merged**
