### PR TITLE
[5.5][Explicit Module Builds] Cherry-pick explicit module build changes

### PR DESCRIPTION
**Pull request by artemcm**
#696: [Explicit Module Builds] Add libSwiftScan API for scanner cache serialization/deserialization
#705: [Explicit Module Builds] Use context hash in Swift dependency module file names
#739: [Explicit Module Builds] Unblock package bots by making tests more resilient to environment changes
#749: [Gardening] Delete deprecated API for tracking external target information
#763: [Dependency Scanning] Restore passing external target map as inputs to the scanning action
#779: [Explicit Module Builds] Add API to specify richer external target module details
#780: [Explicit Module Builds] Pass in -fno-implicit-module-maps for pre-building Clang explicit dependencies
#788: [Explicit Module Builds] Include source modulemap path into PCM filename hash.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
The test failures here are due to dependency on:
https://github.com/apple/swift/pull/38704
We will need that PR to get merged and make it into a nightly toolchain.

**Review by nkcsgexi — APPROVED** [review]
LGTM for the 5.5 branch, though we need to pick up the corresponding compiler changes first to get the tests pass.

**Review by airspeedswift — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
This currently conflicts with where SwiftPM expected libSwiftScan to be located on Linux...
As can be seen [here](https://github.com/apple/swift-package-manager/pull/3668). Looking at fixing how we find this library in the driver.

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
