### PR TITLE
[5.5] implement validation for -sanitize-recover and -sanitize-address-use-odr-indicator

### PR DESCRIPTION
**Pull request by aralisza**
cherry-pick of #645 #653 #647, together to avoid merge issues

• **Explanation**: port validation for -sanitize-recover and -sanitize-address-use-odr-indicator over from the c swift driver
• **Scope**: this change should only affect those who use these two flags. they shouldn't see any new warnings/errors compared to the old swift driver
• **Risk**: Low
• **Reviewed By**: @delcypher @cltnschlosser @artemcm 
• **Testing**: Unit tests in PRs cover new behavior

### CODE REVIEW

**Comment by aralisza** [comment]
@swift-ci please test

**Comment by aralisza** [comment]
@swift-ci please test

**Review by delcypher — APPROVED** [review]
LGTM

**Comment by aralisza** [comment]
@swift-ci please test

**Review by cltnschlosser — COMMENTED** [review]
LGTM, not sure if I’m allowed to approve PRs to a release branch

**Comment by artemcm** [comment]
> LGTM, not sure if I’m allowed to approve PRs to a release branch

The PRs to the release branches are currently set to be gated on approval by a member of [@apple/swift5-branch-managers](https://github.com/apple/swift-driver/blob/release/5.5/CODEOWNERS), but that automation seems to be not working on GitHub side for some PRs.

**Review by cltnschlosser — APPROVED** [review]

**Comment by aralisza** [comment]
@swift-ci please test

**Review by devincoughlin — APPROVED** [review]

**Pull request merged**
