### PR TITLE
Disable adding '-external-plugin-path' in integrated driver mode

### PR DESCRIPTION
**Pull request by rintaro**
rdar://109060298

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Review by artemcm — APPROVED** [review]

**Comment by artemcm** [comment]
@rintaro could you please add a quick test that ensures `Driver` instantiated with this bit set does not add the flags?

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Pull request merged**
