### PR TITLE
Revert "Make the DWARF version configurable."

### PR DESCRIPTION
**Pull request by adrian-prantl**
Reverts apple/swift-driver#1467

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/69416
@swift-ci test

**Review by artemcm — APPROVED** [review]

**Comment by artemcm** [comment]
> test with [apple/swift#69416](https://github.com/apple/swift/pull/69416) @swift-ci test

FYI: Cross-repo testing does not work from here. It needs to be done from `swift` repo.

**Comment by adrian-prantl** [comment]
@swift-ci test macos

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Pull request merged**
