### PR TITLE
Replace TSC signal handler with Dispatch's

### PR DESCRIPTION
**Pull request by stevapple**

### CODE REVIEW

**Comment by compnerd** [comment]
Please do test this on Windows

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Given #1005, I ended up testing it locally.  This does seem to be fine on Windows, but we really do need testing on Windows.

**Review by compnerd — APPROVED** [review]

**Comment by stevapple** [comment]
I bet this is ready for merge?

**Comment by stevapple** [comment]
Anyone to test & merge?

**Comment by cltnschlosser** [comment]
@swift-ci please test

**Pull request merged**
