### PR TITLE
[5.5, Incremental]: Fix clean build performance regression

### PR DESCRIPTION
**Pull request by davidungar**
The narrowest fix I could come with to fix the issue of reading a `swiftmodule` file for each source file.
1. If building a graph without a priors when incremental imports are enabled, don't read existing `swiftmodule ` files.
2. When reading a `swiftmodule` file, mark it as unchanged, so it won't be read again.
3. Add a check in the incremental imports test to ensure that the same `swiftmodule` is not read twice.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@CodaFi Here is my first cut to fix the performance issue in 5.5. I would really value your thoughts on its risk-vs-reward. TIA!

**Comment by davidungar** [comment]
@swift-ci please test macos platform

**Comment by davidungar** [comment]
@swift-ci please test macos platform

**Comment by davidungar** [comment]
@swift-ci please test macos platform

**Comment by davidungar** [comment]
@swift-ci please test linux platform

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
Resolves rdar://80094226 by only reading each `.swiftmodule` file once, instead of once per input file.

**Review by akyrtzi — APPROVED** [review]

**Comment by davidungar** [comment]
Thank you, @akyrtzi and @CodaFi

**Pull request merged**
