### PR TITLE
-c with LTO should still emit bitcode

### PR DESCRIPTION
**Pull request by artemcm**
Straight-forward adaptation of:
https://github.com/apple/swift/pull/35026

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Review by davidungar — APPROVED** [review]
I'm not as familiar with bitcode emission as I would like to be, but this change looks OK to me!

**Review by owenv — APPROVED** [review]

**Comment by CodaFi** [comment]
⛵

**Comment by CodaFi** [comment]
@swift-ci test

**Pull request merged**
