### PR TITLE
Remove package-collection and package-registry from top-level command help

### PR DESCRIPTION
**Pull request by bitjammer**
rdar://104603198

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please test

**Review by artemcm — APPROVED** [review]

**Comment by bitjammer** [comment]
@swift-ci Please test macOS Platform

**Comment by tkremenek** [comment]
@swift-ci test macos

**Comment by artemcm** [comment]
@shahmishal CI on `release/5.8` seems to be pulling in `swift-DEVELOPMENT-SNAPSHOT-2023-02-23-a-osx.pkg`. 

Could we please switch that over to `swift-5.8-DEVELOPMENT-SNAPSHOT-...`?

**Comment by shahmishal** [comment]
@swift-ci test macos

**Pull request merged**
