### PR TITLE
Finish Up Driver Dependency Graph Serialization

### PR DESCRIPTION
**Pull request by CodaFi**
- Serialize external dependencies
- Serialize uses-by-defs

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@davidungar I believe this supersedes #450

**Comment by CodaFi** [comment]
Now that we've got the internals nailed down, the remaining concerns I have revolve around serialization orders being run-dependent. I don't know how much it matters in practice yet since the legacy driver didn't really pay much mind here for source file dependency graphs.

**Review by davidungar — APPROVED** [review]
I just gave it a quick look & it looks great! Glad to have it. Thanks.

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
