### PR TITLE
Add two new SwiftFlags in makeOptions

### PR DESCRIPTION
**Pull request by natecook1000**
It looks like the Swift frontend added a couple new `SwiftFlags`, which is breaking the `makeOptions` product: https://github.com/apple/swift/blob/93eae81b0485507ea982440cc6968a4d94252999/include/swift/Option/Options.h#L42-L43. This matches those in this project.

### CODE REVIEW

**Review by cltnschlosser — APPROVED** [review]

**Review by artemcm — APPROVED** [review]

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test and merge

**Comment by varungandhi-apple** [comment]
@swift-ci test and merge

**Comment by varungandhi-apple** [comment]
@swift-ci test

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
