### PR TITLE
begin to integrate SwiftSystem

### PR DESCRIPTION
**Pull request by tomerd**
motivation: SwiftSystem provides infra that can replace some bespoke implementations in TSC and, improving the cross-platform support. as such we are adding it as a dependency to TSC

changes: add SwiftSystem to CMake setup so it can be included in CMake based builds

### CODE REVIEW

**Comment by tomerd** [comment]
requires:
* apple/swift-system#73
* https://github.com/apple/swift-tools-support-core/pull/262

**Comment by tomerd** [comment]
cc @compnerd

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/3881
https://github.com/apple/swift-tools-support-core/pull/262
https://github.com/apple/sourcekit-lsp/pull/437

@swift-ci please test

**Comment by tomerd** [comment]
apple/swift-package-manager#3881
apple/swift-tools-support-core#262
apple/sourcekit-lsp#437

@swift-ci please test

**Comment by artemcm** [comment]
Just a heads up: our CI does not exercise swift-driver's CMake build so you'll need to do cross-repository testing from the `swift` repo to make sure this works from `build-script`.

**Review by artemcm — APPROVED** [review]

**Review by davidungar — APPROVED** [review]
Seems like a good idea to me.

**Comment by tomerd** [comment]
> Just a heads up: our CI does not exercise swift-driver's CMake build so you'll need to do cross-repository testing from the swift repo to make sure this works from build-script.

yes, that part was tested in apple/swift-package-manager#3881 and we will also run another toolchain build

**Pull request merged**
