### PR TITLE
Add support for compile jobs that read source input from standard input.

### PR DESCRIPTION
**Pull request by artemcm**
This change uses `Process` input handling added in https://github.com/apple/swift-tools-support-core/pull/208 to allow forwarding of the driver's Standard Input to a frontend job.

Resolves rdar://76454784

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@shahmishal, the CI log says it is pulling swift-tools-support-core from `main`, but the build fails as if https://github.com/apple/swift-tools-support-core/pull/208 hasn't been merged. Am I missing something in how this works?

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
Its running on clean workspace, let me log in and check the sha.

**Comment by shahmishal** [comment]
```
  {
        "package": "swift-tools-support-core",
        "repositoryURL": "https://github.com/apple/swift-tools-support-core.git",
        "state": {
          "branch": "main",
          "revision": "207f9c6bc5e33eb8383266c0cd3129c1276f534b",
          "version": null
        }
      }
```

**Comment by artemcm** [comment]
> "revision": "207f9c6bc5e33eb8383266c0cd3129c1276f534b",
Right, this is quite old so if it's resolved to this commit then it makes sense why it doesn't work.

**Comment by artemcm** [comment]
@swift-ci please test

**Review by cltnschlosser — APPROVED** [review]

**Pull request merged**
