### PR TITLE
Conform VirtualPath to CustomStringConvertible

### PR DESCRIPTION
**Pull request by vbergae**
Hi! 

Just a PR to fix a really simple `FIXME`. Not sure if the `FIXME` will finally apply or keeping the attribute `name` is the desired solution. Any comment or suggestion to finish the PR is more than welcome :)

### CODE REVIEW

**Comment by harlanhaskins** [comment]
Thanks for doing this! I am torn between "we should use the standard set of protocols" and "we should have this semantic property `name` that's very clear at the call site.

What if we added `name` back, but just as

```swift
var name: String { description }
```

**Comment by vbergae** [comment]
True, I felt something similar looking from callee point of view. Let's see if the current solution is a good compromise 😄

**Comment by DougGregor** [comment]
@swift-ci please test and merge

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci Please test

**Pull request merged**
