### PR TITLE
Add support for catalyst

### PR DESCRIPTION
**Pull request by cltnschlosser**
C++ implementation: https://github.com/apple/swift/pull/29017

Also fixes test/Driver/print_target_info.swift

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
Ah, there are conflicts due to other things that have gone in. This LGTM when those are resolved.

**Comment by cltnschlosser** [comment]
@DougGregor Okay, resolved. Looks like CI needs to be kicked off again.

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci please test

**Pull request merged**
