### PR TITLE
[Incremental] Bring swift-driver into correspondence with legacy driver.

### PR DESCRIPTION
**Pull request by davidungar**
With these changes, all 50 test in `Driver/Dependencies` run (assuming https://github.com/apple/swift/pull/35171 ).
See the individual commits for the details.

rdar://71869951
rdar://71870416
rdar://72508507

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@swift-ci please test

**Review by owenv — APPROVED** [review]
LGTM! 🎉

**Comment by davidungar** [comment]
Thank you, @owenv !

**Comment by davidungar** [comment]
rdar://72508532

**Pull request merged**
