### PR TITLE
Update SourceFileDependencyGraph deserialzation

### PR DESCRIPTION
**Pull request by owenv**
This PR includes a few related improvements to reading SourceFileDependencyGraphs:
- It switches to the copies of the Bitstream utilities moved to TSC (where they'll also be used to read .dia files for SPM)
- swiftdeps files are now read in a single pass using a new BitstreamVisitor protocol exposed by TSC in the corresponding PR in that repo
- SourceFileDependencyGraphs can now be read from swiftmodule files when the experimental cross-module dependencies are enabled. This isn't hooked up to anything yet, but it was a useful way to test the other changes

Most of the interesting changes to the Bitstream APIs are in the corresponding TSC PR here: https://github.com/apple/swift-tools-support-core/pull/145. This won't compile until those are merged and then synced to the vendored TSC in SPM

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]
Always happy to see minuses. Looks good!

**Review by davidungar — APPROVED** [review]
LGTM!

**Comment by owenv** [comment]
This should pass tests now, but I need to sync TSC changes to the vendor copy in SPM before merging

@swift-ci please test

**Comment by owenv** [comment]
The TSC changes have now been synced to SPM and full CI is passing here: https://github.com/apple/swift/pull/34531. I'm going to rerun tests here one more time just to double check nothing's wrong with the non-cmake build.

@swift-ci please test

**Pull request merged**
