### PR TITLE
cmake: set up build-script support for swift-build-sdk-interfaces

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@artemcm do we have CI coverage for changes like this in the swift-driver repo?

**Comment by artemcm** [comment]
> @artemcm do we have CI coverage for changes like this in the swift-driver repo?

Alas, we do not (they are coming!).
For now, I'd suggest opening a draft PR against https://github.com/apple/swift and running a cross-repository test.

**Comment by nkcsgexi** [comment]
> > @artemcm do we have CI coverage for changes like this in the swift-driver repo?
> 
> Alas, we do not (they are coming!).
> For now, I'd suggest opening a draft PR against https://github.com/apple/swift and running a cross-repository test.

Will do!

**Review by artemcm — APPROVED** [review]

**Comment by compnerd** [comment]
This seems to have regressed the Windows build: https://dev.azure.com/compnerd/3133d6ab-80a8-4996-ac4f-03df25cd3224/_apis/build/builds/49662/logs/44

**Pull request merged**
