### PR TITLE
[Incremental] Rename "SwiftDeps" etc. to "DependencySource"

### PR DESCRIPTION
**Pull request by davidungar**
In order to implement cross-module incrementality, the SwiftDeps type needs to also represent a swiftSourceFile file, so the name is how wrong.

### CODE REVIEW

**Comment by davidungar** [comment]
Have not reformatted yet.

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@swift-ci please test

**Review by CodaFi — APPROVED** [review]

**Pull request merged**
