### PR TITLE
[5.5] Propagate `-warn-concurrency` to frontend invocations.

### PR DESCRIPTION
**Pull request by artemcm**
Cherry-pick of https://github.com/apple/swift-driver/pull/770
------------------------------------
Resolves rdar://80925867

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test macOS platform

**Comment by artemcm** [comment]
@swift-ci please test macOS platform

**Comment by artemcm** [comment]
macOS bot seems to be having a bad time. Will try again in a little bit.

**Comment by artemcm** [comment]
@swift-ci please test macOS platform

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
