### PR TITLE
[Incremental, Testing] Result builder & dependent removal test

### PR DESCRIPTION
**Pull request by davidungar**
1. Use a result builder for the expected diagnostics, and
2. Add another condition to the file removal test in which the removed file depends on a file that changes

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
Err, I'd try building your PR with the latest toolchain snapshot from swift.org locally to see if the same failure can be reproduced. Perhaps the latest toolchain has a buggy compiler.

**Comment by davidungar** [comment]
> Err, I'd try building your PR with the latest toolchain snapshot from swift.org locally to see if the same failure can be reproduced. Perhaps the latest toolchain has a buggy compiler.

Good idea! At the moment, I can't even load the web page with the log, though.

**Comment by davidungar** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]
This change looks fine to me!

**Comment by davidungar** [comment]
Thank you, @artemcm !

**Pull request merged**
