### PR TITLE
SwiftDriver: on FreeBSD, use lld, not gold

### PR DESCRIPTION
**Pull request by mhjacobson**
This is equivalent to passing `-use-ld=lld` to the driver.

### CODE REVIEW

**Comment by mhjacobson** [comment]
See also apple/swift#61864.

**Comment by CodaFi** [comment]
Looks good. Please add a test a la https://github.com/apple/swift-driver/commit/01e03d380ea6d08030b237af5cf86fb6ba53e5f5#diff-0521ecca5b0c330d8bf1c0dc0ab703a9e3e35d8ea873e192480c0091c064fa1e

**Comment by mhjacobson** [comment]
Added, thanks!

**Review by artemcm — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci test

**Review by compnerd — APPROVED** [review]

**Pull request merged**
