### PR TITLE
91574616 emit module dependencies & diagnostics

### PR DESCRIPTION
**Pull request by BenchR267**
This PR brings rdar://83110325 and rdar://91574616 to `release/5.7`.

Original PRs:
https://github.com/apple/swift-driver/pull/1046
https://github.com/apple/swift-driver/pull/1056

### CODE REVIEW

**Comment by BenchR267** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]
Thanks @BenchR267

**Review by owenv — APPROVED** [review]

**Comment by BenchR267** [comment]
@swift-ci please test

**Comment by BenchR267** [comment]
@swift-ci please test

**Pull request merged**
