### PR TITLE
[5.5] cherry-pick -clang-target support

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://72480261

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]
LGTM for the 5.5 branch.
These changes are either additive or guarded with feature flags so they should have minimal effect on 5.5 code-paths.

**Comment by artemcm** [comment]
@swift-ci please test

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
