### PR TITLE
Add support for the new `-index-ignore-clang-modules` flag

### PR DESCRIPTION
**Pull request by DavidGoldman**
This flag was recently added in https://github.com/apple/swift/pull/58932.

### CODE REVIEW

**Comment by artemcm** [comment]
Could you please update the Options according to the procedure in:
https://github.com/apple/swift-driver#rebuilding-optionsswift ? 

It's okay if that also brings in some unrelated changes.

**Review by artemcm — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by DavidGoldman** [comment]
Looks like the failures are related to the cxx flag changes?

**Comment by artemcm** [comment]
> Looks like the failures are related to the cxx flag changes?

Gah, okay, feel free to un-do the `Options.swift` additions/removals unrelated to your change.

**Comment by DavidGoldman** [comment]
Can you trigger CI again? Thanks

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by DavidGoldman** [comment]
> > Looks like the failures are related to the cxx flag changes?
> 
> Gah, okay, feel free to un-do the `Options.swift` additions/removals unrelated to your change.

Yep looks like that fixed it

**Pull request merged**
