### PR TITLE
Add generated file note to Options.swift

### PR DESCRIPTION
**Pull request by etcwilde**
Updating makeOptions to include note that options.swift is generated so it should not be edited by hand.

Adding a note to the file so that folks are reminded not to edit it by hand.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
I should probably add the generated header comment to `Options.swift`.

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]
Thank youuuuuu

**Comment by etcwilde** [comment]
@swift-ci please test Windows

**Pull request merged**
