### PR TITLE
[NFC] Refactor some incremental compilation tests, prior to adding more tests

### PR DESCRIPTION
**Pull request by davidungar**
The behavior-neutral changes that will be wanted when more tests are added:

1. Add an `inputPath` method and use it where needed.
2. Add a `write` method to factor out future input writing.
3. Eliminate many cases where the tests would just crash. Raise exceptions instead. Add 'try's.
4. Rewrite `doABuild` and return a non-optional.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]
Nice cleanup, thanks!

**Comment by davidungar** [comment]
My pleasure and thank you, @artemcm !

**Comment by davidungar** [comment]
rdar://77998890

**Pull request merged**
