### PR TITLE
[5.7] On interrupt, after handling the compilation process set termination, restore the SIGINT default action.

### PR DESCRIPTION
**Pull request by artemcm**
Cherry-pick of https://github.com/apple/swift-driver/pull/1157
-----------------------------------------

Resolves rdar://98584872

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Review by nkcsgexi — APPROVED** [review]
Safe change to cherry-pick.

**Comment by artemcm** [comment]
@swift-ci test macOS platform

**Comment by artemcm** [comment]
@swift-ci test macOS platform

**Comment by artemcm** [comment]
@swift-ci test macOS platform

**Comment by artemcm** [comment]
Test failures are unrelated, and appear to be caused by the fact that this CI is using the latest ToT snapshot toolchain, instead of a 5.7 toolchain.

**Comment by artemcm** [comment]
> Test failures are unrelated, and appear to be caused by the fact that this CI is using the latest ToT snapshot toolchain, instead of a 5.7 toolchain.

cc @shahmishal , this is an example PR.

**Pull request merged**
