### PR TITLE
Support for binary module validation in scanner

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Fix all the tests that expect building module from interface even when the binary module is up-to-date after the swift scanner behavior change.

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
This is to support the change in https://github.com/apple/swift/pull/72291

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test windows platform

**Comment by cachemeifyoucan** [comment]
ping @artemcm This is needed to allow the swift change to pass PR. Should have no functional changes except added the new flag option and use that to update the test so test can pass with or without the change.

**Review by artemcm — APPROVED** [review]

**Pull request merged**
