### PR TITLE
Report a better error message when retrieving target info from the frontend fails

### PR DESCRIPTION
**Pull request by owenv**
This should help make it a bit clearer what's going on when using the driver with an incompatible toolchain or configuring SWIFT_DRIVER_SWIFT_FRONTEND_EXEC incorrectly

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci test

**Comment by owenv** [comment]
@swift-ci test macOS

**Comment by owenv** [comment]
It looks like the 8/7 snapshot CI is using has some kind of code signing issue. I filed https://bugs.swift.org/browse/SR-13370 in case it doesn't resolve itself on its own tomorrow

**Comment by DougGregor** [comment]
@swift-ci test macOS

**Comment by DougGregor** [comment]
Hmm, still having trouble:

**Pull request merged**
