### PR TITLE
[Incremental] Add code to compare ModuleDepGraphs, & strengthen testRoundTripFixtures with it

### PR DESCRIPTION
**Pull request by davidungar**
Someday, it would be nice to round-trip-test every time we write a ModuleDepGraph when assertions are enabled.
For now, just strengthen the test, because I don't think that everything is getting serialized, e.g. `usesByDef`.
@CodaFi This code is in rough form; I expect we'll want to clean it up a lot. But for now, you can use it to hone the serialization code.

### CODE REVIEW

**Review by CodaFi — APPROVED** [review]

**Comment by CodaFi** [comment]
@swit-ci test

**Comment by CodaFi** [comment]
@swit-ci test

**Comment by CodaFi** [comment]
@swit-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@swift-ci please test

**Pull request merged**
