### PR TITLE
[Incremental] Properly detect the testing case when honoring -driver-use-frontend-path

### PR DESCRIPTION
**Pull request by davidungar**
Turns out the tests invoke `Python` as the command, so test for that. No need to add .py to file types.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@swift-ci please test

**Review by cltnschlosser — APPROVED** [review]

**Comment by davidungar** [comment]
Thanks @cltnschlosser !

**Pull request merged**
