### PR TITLE
Add support for -lto_library linker flag

### PR DESCRIPTION
**Pull request by jslegendre**
Allow users to specify a particular LTO library on Darwin.

### CODE REVIEW

**Comment by jslegendre** [comment]
@swift-ci please test
@owenv

**Review by artemcm — APPROVED** [review]
This change looks good to me, thank you @jslegendre.

Please make sure that the `Options.swift` file is generated using the automated procedure described here:
https://github.com/apple/swift-driver#rebuilding-optionsswift

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by jslegendre** [comment]
@artemcm Apologies for the oversight. Should be all set now.  The relevant PR which adds this flag to Options.td is still open here https://github.com/apple/swift/pull/38264

**Comment by jslegendre** [comment]
@artemcm Anything else I should do now the tests have passed?

**Comment by jslegendre** [comment]
https://github.com/apple/swift/pull/38264 has been merged. This should be good to go.

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
