### PR TITLE
Add missing dependency

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]

**Review by owenv — CHANGES_REQUESTED** [review]
The dependency needs to be added around line 144 so it can be properly handled in local-deps mode

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test windows

**Review by owenv — APPROVED** [review]

**Pull request merged**
