### PR TITLE
Thread a filesystem throughout the Swift driver.

### PR DESCRIPTION
**Pull request by DougGregor**
The Swift driver library should never directly access the local file
system. Thread a file system parameter through the SwiftDriver library
so clients can provide an alternative file system if they want.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by ddunbar** [comment]
Does this unblock additional or perhaps better testing?

**Comment by DougGregor** [comment]
@swift-ci test Linux

**Comment by DougGregor** [comment]
> Does this unblock additional or perhaps better testing?

I'm planning to use it with a partial pass-through file system so we don't have to write as much to disk while doing build planning. That's causing some problems for me with SwiftPM and the integrated driver (hence, the need for this PR).

**Pull request merged**
