### PR TITLE
[Incremental, Optimization] Defer use hashing when reading a ModuleDependencyGraph

### PR DESCRIPTION
**Pull request by davidungar**
When deserializing a `ModuleDependencyGraph`, don't record uses in a dictionary twice. Just save in an array while reading. On a project with 1,000 files, when rebuilding after just adding a newline to one file, swift-driver-new time in Instruments was reduced from 5.3 secs to 4.7.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please test

**Review by cltnschlosser — APPROVED** [review]

**Comment by davidungar** [comment]
Thank you, @cltnschlosser !

**Comment by davidungar** [comment]
@CodaFi , would you like to review before this lands?

**Review by CodaFi — APPROVED** [review]
I suspect the win you're seeing is because we're no longer hashing DependencyKeys. There's no double registration here AFAICT.

**Comment by davidungar** [comment]
> I suspect the win you're seeing is because we're no longer hashing DependencyKeys. There's no double registration here AFAICT.
Not sure why you thought of double registration. But there was double dictionary access. Thanks for reviewing!

**Comment by CodaFi** [comment]
There is no double access. The mutation here goes through the modify coroutine. We don't lookup once to read and once to append https://github.com/apple/swift/blob/main/stdlib/public/core/Dictionary.swift#L893

**Comment by davidungar** [comment]
> There is no double access either. The mutation here goes through the modify coroutine. We don't lookup once to read and once to append https://github.com/apple/swift/blob/main/stdlib/public/core/Dictionary.swift#L893

I understand that. The other access is here: ```
         let isNewUse = self.graph.nodeFinder
            .record(def: dependencyKey, use: self.allNodes[useID])
```
inside `record`. There was one dictionary access while reading, and another while finalizing.

**Pull request merged**
