### PR TITLE
[NFC] Sequester Incremental Build Reporting Into a Type

### PR DESCRIPTION
**Pull request by CodaFi**
Untangle the nest of callbacks into a single type.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Review by cltnschlosser — APPROVED** [review]
I like it, nice clean up.

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
