### PR TITLE
Fixup module source info output

### PR DESCRIPTION
**Pull request by cltnschlosser**
@DougGregor @artemcm 

Pulled from #144

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by cltnschlosser** [comment]
Can someone kick off CI again. Thanks!

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@cltnschlosser, the CI is currently broken due to a potential bug in SwiftPM exposed by the newest available toolchain snapshot, we're investigating the break. Will ping once it is cleared.

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
