### PR TITLE
Module aliasing: use real module names to resolve graph during dependency scan

### PR DESCRIPTION
**Pull request by elsh**
Use real module names during dependency scan / construct deps graph and imports
Add tests using driver dependency scanner and fallback frontend scanner
Make isFramework optional in SwiftModuleDetails and SwiftPrebuiltExternalModuleDetails (else throws JSON Decoding error)

Resolves rdar://85525296

### CODE REVIEW

**Comment by elsh** [comment]
Depends on https://github.com/apple/swift-driver/pull/912

**Comment by elsh** [comment]
@swift-ci  test

**Comment by elsh** [comment]
@swift-ci test

**Review by beccadax — APPROVED** [review]
You should wait for a review from Artem to check that threading a dictionary parameter through is the best way to structure this within the driver (as opposed to making it a property somewhere), but otherwise this LGTM.

**Comment by artemcm** [comment]
The existing changes look good to me, but I think there are a couple of things missing:
- What happens when dependencies are queried on the fallback path of invoking `swift-frontend -scan-dependencies`? 
In places where we get the graph via:
```
dependencyGraph = try self.executor.execute(job: scannerJob, ...
```
You may need to mutate the graph we get using the module information. It would be nice to have a test for that as well. 
- As you mentioned offline, the import-rescan flow needs the same kind of `moduleAliases` param and name resolution logic.

**Comment by elsh** [comment]
Depends on https://github.com/apple/swift/pull/40384

**Review by artemcm — APPROVED** [review]

**Comment by elsh** [comment]
> The existing changes look good to me, but I think there are a couple of things missing:
> 
> * What happens when dependencies are queried on the fallback path of invoking `swift-frontend -scan-dependencies`?
>   In places where we get the graph via:
> 
> ```
> dependencyGraph = try self.executor.execute(job: scannerJob, ...
> ```
> 
> You may need to mutate the graph we get using the module information. It would be nice to have a test for that as well.
> 
> * As you mentioned offline, the import-rescan flow needs the same kind of `moduleAliases` param and name resolution logic.

Thanks for the pointers; addressed feedback / tests pending https://github.com/apple/swift/pull/40384

**Comment by elsh** [comment]
@swift-ci test

**Comment by elsh** [comment]
Pending https://github.com/apple/swift/pull/40412

**Comment by elsh** [comment]
@swift-ci test

**Comment by elsh** [comment]
@swift-ci test

**Comment by elsh** [comment]
@swift-ci test

**Pull request merged**
