### PR TITLE
Update Options.swift for '-disable-sandbox'

### PR DESCRIPTION
**Pull request by rintaro**
Update for https://github.com/apple/swift/pull/70046

Updated by 'makeOptions'

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Review by artemcm — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Pull request merged**
