### PR TITLE
Resolve main executable symlink when looking up driver-adjacent subcommand binaries

### PR DESCRIPTION
**Pull request by artemcm**
Resolves https://github.com/apple/swift/issues/70932

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Review by nkcsgexi — APPROVED** [review]
Thank you!

**Comment by stevapple** [comment]
I'm afraid this would break Windows support. IIRC we were using `findExecutable` for both cases because it can handle the executable suffix for us.

**Comment by kkebo** [comment]
@artemcm Do you plan to cherry-pick this to 6.0?

**Pull request merged**
